apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-autoscale
  labels:
    app : my-k8s-as
    owner : IgorMarchenko
spec:
  replicas : 3
  selector:
    matchLabels:
      project: as
      app: my-k8s-as
  template:
    metadata:
      labels:
        project: as
        app: my-k8s-as
    spec:
      containers:
        - name: my-as
          image: raacharg/k8sphpapp:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: my-as
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource: 
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
