apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app : my-k8s-app
    owner : Igor
spec:
  selector:
    matchLabels:
      project: LearningK8s
      app: my-k8s-app
  template:
    metadata:
      labels:
        project: LearningK8s
        app: my-k8s-app
    spec:
      containers:
      - name: my-web
        image: raacharg/k8sphpapp:latest
        ports:
        - containerPort: 80
