apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-replicas
  labels:
    app : my-k8s-app
    owner : IgorMarchenko
spec:
  replicas : 3
  selector:
    matchLabels:
      project: LearningReplicasK8s
      app: my-k8s-app
  template:
    metadata:
      labels:
        project: LearningReplicasK8s
        app: my-k8s-app
    spec:
      containers:
      - name: my-web
        image: raacharg/k8sphpapp:latest
        ports:
        - containerPort: 80
